server:
  port: 8086
spring:
  application:
    name: community-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.105.58:3306/yunzhang?characterEncoding=UTF8&useSSL=false
    username: root
    password: '@asdend123'
  jpa:
    database: MySQL
    show-sql: true
mybatis:
  mapper-locations: classpath:dao/*.xml